application:
  key: ${api.key}
  mongo-host: ${mongo.host:db}
  mongo-port: ${mongo.port:27017}
  mongo-username: ${mongo.username}
  mongo-password: ${mongo.password}

server:
 ssl:
   enabled: true
   key-store: classpath:keystore.p12
   key-store-password: changeit
   key-password: changeit
   key-alias: keystore
 port: 8443
 compression:
   enabled: true
   min-response-size: 1KB

logging:
  level:
    com.dodecaedro: TRACE

spring:
  main:
    lazy-initialization: true
  jackson:
     default-property-inclusion: non_null
     deserialization:
       fail-on-unknown-properties: false
