application:
  key: ${api.key}
  mongo-host: ${mongo.host:db}
  mongo-port: ${mongo.port:27017}
  mongo-username: ${mongo.username}
  mongo-password: ${mongo.password}

logging:
  level:
    com.jbequinn.jsonsyncserver: INFO
